apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-chatapp-retail
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /rag-chatapp-retail(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rag-chatapp-retail
                port:
                  number: 80
