apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentframework-chatbot
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /agentframework-chatbot
            pathType: Prefix
            backend:
              service:
                name: agentframework-chatbot
                port:
                  number: 80
